#!/usr/bin/perl

use Getopt::Long;

require INFN::LScan;

my $lscan = new INFN::LScan;

my ($dir, $help, $check, $setup, $ok, $sqlite_file);

my $opt = GetOptions(	"directory=s" => \$dir,
					"file=s" => \$sqlite_file,
					"setup" => \$setup,
					"check" => \$check,
					"ok" => \$ok,
					"help" => \$help);
					
$sqlite_file |= 'lscan.sqlite';
$ok |= 0;

$lscan->open_database("$sqlite_file");

if ($dir)
{
	$lscan->add_files($dir);
	$lscan->f_to_database();
}

if ($check)
{
	$lscan->check_database($ok);
}

if ($help)
{
	print "Using module " . $lscan->get_name() . " " . $lscan->get_version() . "\n";
	print "-s setup or for new database creation\n";
	print "-d <directory> add directory and recursive sub dirs\n";
	print "-f <filename> sqlite database filename to use. lscan.sqlite will be used if none is specified\n";
	print "-c check\n";
	print "-o print ok file with md5 match\n";
	print "-h this help output\n";
	
	die;
}

if ($setup)
{
	$lscan->dbc("CREATE TABLE files (id INTEGER PRIMARY KEY, filename)");
	$lscan->dbc("CREATE TABLE md5 (id INTEGER PRIMARY KEY, hash)");
}